### Create Charity
GRAPHQL {{graphql}}
Authorization: {{accessToken}}

mutation CreateCharity($input: CreateCharityDto!) {
    createCharity(createCharityDto: $input){
        id
        name
        documents {
            id
            document
            type
        }
    }
}

{
  "input": {
    "name": "Amigo Pet",
    "CNPJ": "435754456"
  }
}