### Create Charity
GRAPHQL {{graphql}}
Authorization: {{accessToken}}

mutation CreateCharity($input: CreateCharityDto!) {
    createCharity(createCharityDto: $input){
        id
        name
    }
}

{
  "input": {
    "name": "Criança Felizzzz",
    "CNPJ": "123333444434"
  }
}