### Find All Charities
GRAPHQL {{graphql}}
Authorization: {{accessToken}}

query FindAllCharities {
    findAllCharities {
        id
        name
        documents {
            id
            type
            document
        }
        donations {
            id
            amount
            donorId
            charityId
        }
    }
}

{

}