### Find All Donations
GRAPHQL {{graphql}}
Authorization: {{accessToken}}

query FindAllDonations {
    findAllDonations {
        id
        amount
        charity {
            id
            name
        }
        donor {
            id
            name
        }
    }
}

{

}