GRAPHQL {{graphql}}

mutation CreateAccess($input: CreateAccessDto!) {
    createAccess(input: $input){
        id
        email
        donor {
            id
            name
            accessId
        }
    }
}

{
  "input": {
    "name": "John Doe",
    "birthDate": "2000-01-01",
    "email": "john.doe@email.com",
    "password": "12345678"
  }
}